name: wechat
description: A new Flutter application.

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  # webview组件
  flutter_webview_plugin: "^0.2.1+2"
  # 图像选择器插件
  image_picker: "^0.4.4" 
  # 数据简单持久化
  shared_preferences: "^0.4.2"
  # 通知
  flutter_local_notifications: "^0.3.1"
  # 网络请求库
  dio: ^2.0.22
  # 时间格式化
  date_format: "^1.0.4"
  # 带有粘贴标题的列表视图，如Android联系人页面
  side_header_list_view: "^0.0.3"

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    # 4个tab切换图片资源
    - images/weixin_pressed.png
    - images/weixin_normal.png

    - images/contact_list_pressed.png
    - images/contact_list_normal.png

    - images/find_pressed.png
    - images/find_normal.png

    - images/profile_pressed.png
    - images/profile_normal.png
    # 联系人头部icon
    - images/icon_addfriend.png
    - images/icon_qunliao.png
    - images/icon_public.png
   
    - images/ado.png
    - images/ad6.png
    - images/find_friends.png
    - images/icon_de_saoyisao.png
    - images/icon_me_card.png
    - images/icon_me_collect.png
    - images/icon_me_money.png
    - images/icon_me_photo.png
    - images/icon_me_setting.png
    - images/icon_me_smail.png
    - images/apv.png
    - images/ahl.png
    - images/as1.jpg
    - images/welcome.jpg
    - images/icon_menu_addfriend.png
    - images/icon_menu_group.png
    - images/icon_menu_sao.png
    - images/icon_de_yao.png
    - images/icon_de_shop.png
    - images/icon_de_nearby.png
    - images/icon_de_ping.png
    - images/v2.png
    - images/icon_k.png
    - images/icon_s.png
    - images/icon_link.png

    # widget
    - images/flutter.png
    - images/container.png
    - images/column.png
    - images/row.png
    - images/image.png
    - images/text.png
    - images/button.png
    - images/appbar.png
    - images/scaffold.png
    - images/md_icon.png

    - images/BottomNavigationBar.png
    - images/Drawer.png
    - images/MaterialApp.png
    - images/tabbar.png
    - images/TabBarView.png

    - images/FlatButton.png
    - images/FloatingActionButton.png
    - images/IconButton.png
    - images/PopupMenuButton.png

    - images/Checkbox.png
    - images/Radio.png
    - images/Slider.png
    - images/Switch.png
    - images/TextField.png
    - images/TimePicker.png

    - images/SimpleDialog.png
    - images/AlertDialog.png
    - images/BottomSheet.png
    - images/ExpansionPanel.png
    - images/SnackBar.png

    - images/Chip.png
    - images/Tooltip.png
    - images/DataTable.png
    - images/Card.png
    - images/LinearProgressIndicator.png

    - images/ListTile.png
    - images/Stepper.png
    - images/Divider.png
    
    

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
